### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by huangpd** [Igorxp5/whatsapp-insights#1]
![企业微信截图_16475958805738](https://user-images.githubusercontent.com/29889615/158978208-438f00e9-419d-48a1-8f20-dbb776807748.png)

Like an order like this ,shell order 
![1647596258(1)](https://user-images.githubusercontent.com/29889615/158978460-e8265736-dc03-4efa-9037-449315ff71a0.png)

how did you get it
thanks !

**Comment by Igorxp5** [comment]
Hi, you mean how did I find that?

Actually, I don't remember, that shell came from another project that I made 5 years ago. I just reused it.

I found this [StackOverflow thread](https://stackoverflow.com/questions/52997828/send-text-message-to-whatsapp-and-sms-using-intent-create-chooser-not-working-an). There, a guy says how to do that in an Android project, you can use the same arguments in intent call through ADB, like I did.

**Comment by huangpd** [comment]
thank and you
